spring.application.name=ai-salesops

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_salesops_db
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot Server
server.port=9090