spring.application.name=ai-automation-system

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_automation
spring.datasource.username=postgres
spring.datasource.password=welcome
spring.jpa.hibernate.ddl-auto=update

# OpenAI
#openai.api.key=YOUR_OPENAI_API_KEY_HERE
#openai.model=gpt-4o-mini

#groq
groq.api.key=YOUR_GROQ_API_KEY
groq.model=llama-3.3-70b-versatile

# NEW - Gemini
gemini.api.key=YOUR_GEMINI_API_KEY_HERE
gemini.model=gemini-1.5-flash

# Gmail API
gmail.credentials.file=d:/Projects/AI-Powered_Automation_Systems/project/credentials.json
gmail.tokens.directory=tokens
gmail.application.name=AI Automation System
gmail.user=me

# Scheduler
gmail.scheduler.enabled=true
gmail.scheduler.cron=0 */5 * * * *
# This runs every 5 minutes: (sec min hour day month weekday)

# Auto-reply  # Set true to auto-send drafts
gmail.auto.reply.enabled=false
gmail.processed.label=AI_PROCESSED

# Only job applications
gmail.auto.reply.categories=JOB_APPLICATION

#All Categories
#gmail.auto.reply.enabled=true
#gmail.auto.reply.categories=BILLING,TECHNICAL,JOB_APPLICATION,COMPLAINT,ORDER_STATUS,GENERAL,ENQUIRY
